export { CommentList as CommentListDeprecated } from './ui-deprecated/CommentList/CommentList'
export { AddCommentFormAsync as AddCommentFormDeprecated } from './ui-deprecated/AddCommentForm/AddCommentForm.async'
export { CommentList } from './ui-V2/CommentList/CommentList'
export { AddCommentFormAsync as AddCommentForm } from './ui-V2/AddCommentForm/AddCommentForm.async'
export { type Comment } from './module/types/AddCommentSchema'
export { type AddCommentSchema } from './module/types/AddCommentSchema'
export { getAddCommentFormText } from './module/selectors/getAddCommentFormSelectors'
export { addCommentFormSliceActions } from './module/slice/addCommentFormSlice'
