export enum ValidationError {
  SERVER_ERROR = 'SERVER_ERROR',
  FIRSTNAME_ERROR = 'FIRSTNAME_ERROR',
  LASTNAME_ERROR = 'LASTNAME_ERROR',
  AGE_ERROR = 'AGE_ERROR',
  AVATAR_ERROR = 'AVATAR_ERROR'
}
