name: Linting, Testing CI Pipeline with Chromatic

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ develop ]

permissions:
  id-token: write
  pages: write
  contents: read

jobs:
  pipeline:
    name: CI + Chromatic
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci --force

      - name: Build production project
        run: npm run build:prod
        if: always()

      - name: Run Unit Tests
        run: npm run test:unit
        if: always()

      - name: Setup Pages
        uses: actions/configure-pages@v2
        if: always()
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        if: always()
        with:
          path: 'reports'
      - name: Deploy to GitHub Pages
        id: deployment
        if: always()
        uses: actions/deploy-pages@v2

      - name: Build Storybook
        run: npm run build-storybook
        if: always()

      - name: Publish to Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}

  checks:
    name: Linting
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci --force

      - name: Lint TypeScript
        run: npm run lint:ts
        if: always()

      - name: Lint CSS
        run: npm run lint:scss